kind: containerapp
name: order-processor-http
resourceGroup: <your_resource_group>
type: Microsoft.App/containerApps
location: centralus
properties:
  configuration:
    activeRevisionsMode: Single
    dapr:
      appId: order-processor-http
      appPort: 80
      appProtocol: http
      enabled: true
    ingress:
      allowInsecure: false
      external: true
      targetPort: 80
    secrets:
      - name: storagekey
        value: <your_storage_key>
  managedEnvironmentId: /subscriptions/<your_subscription>/resourceGroups/<your_resource_group>/providers/Microsoft.App/managedEnvironments/<your_ACA_env_name>
  template:
    revisionSuffix: ""
    volumes:
      - name: 'diagport'
        storageType: 'EmptyDir'
    containers:
      - image: cathyxwang/dotnet-pizza-backend-appinsights-debug:latest
        name: order-processor-http
        probes: []
        resources:
          cpu: 0.5
          ephemeralStorage: ""
          memory: 1Gi
        volumeMounts:
          - mountPath: '/diagport'
            volumeName: 'diagport'
        env:
          - name: 'DOTNET_DiagnosticPorts'
            value: '/diagport/port.sock'
          - name: APPLICATIONINSIGHTS_CONNECTION_STRING
            value: your_appinsights_connectionstring
      - image: mcr.microsoft.com/dotnet/nightly/monitor:7.0.0-rc.1
        name: 'dotnet-monitor'
        volumeMounts:
          - mountPath: '/diagport'
            volumeName: 'diagport'
        command: 
          - dotnet-monitor
        args:
          - collect
          - --no-auth
        env:
          - name: 'DotnetMonitor_DiagnosticPort__ConnectionMode'
            value: 'Listen'
          - name: 'DotnetMonitor_Storage__DumpTempFolder'
            value: '/diagport'
          - name: 'DotnetMonitor_Urls'
            value: 'http://*:52323'
          - name: 'DotnetMonitor_DiagnosticPort__EndpointName'
            value: '/diagport/port.sock'
          - name: 'Egress__AzureBlobStorage__monitorBlob__AccountUri'
            value: 'https://<your_storage_account>.blob.core.windows.net'
          - name: 'Egress__AzureBlobStorage__monitorBlob__ContainerName'
            value: 'dotnet-monitor'
          - name: 'Egress__AzureBlobStorage__monitorBlob__BlobPrefix'
            value: 'artifacts'
          - name: 'Egress__AzureBlobStorage__monitorBlob__AccountKey'
            secretRef: storagekey
          - name: 'CollectionRules__ThreadPoolQueuing__Trigger__Type'
            value: 'EventCounter'
          - name: 'CollectionRules__ThreadPoolQueuing__Trigger__Settings__ProviderName'
            value: 'System.Runtime'
          - name: 'CollectionRules__ThreadPoolQueuing__Trigger__Settings__CounterName'
            value: 'threadpool-queue-length' #threadpool-queue-length
          - name: 'CollectionRules__ThreadPoolQueuing__Trigger__Settings__GreaterThan'
            value: '1'
          - name: 'CollectionRules__ThreadPoolQueuing__Trigger__Settings__SlidingWindowDuration'
            value: '00:00:05'
          - name: 'CollectionRules__ThreadPoolQueuing__Actions__0__Type'
            value: 'CollectDump'
          - name: 'CollectionRules__ThreadPoolQueuing__Limits__ActionCount'
            value: '5'
          - name: 'CollectionRules__ThreadPoolQueuing__Actions__0__Settings__Egress'
            value: 'monitorBlob'
    scale:
      maxReplicas: 1
      minReplicas: 1