name: Trigger auto deployment for order-web

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'PizzaWeb/**'
    - '.github/workflows/order-web-AutoDeployTrigger-b2a6f450-9900-4840-8bbf-e34ae7bea360.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.ORDERWEB_REGISTRY_USERNAME }}
          password: ${{ secrets.ORDERWEB_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: cathyxwang/order-web:${{ github.sha }}
          file: ./PizzaWeb/Dockerfile
          context: ./PizzaWeb/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ORDERWEB_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n order-web -g PizzaOrderDemo4 --server docker.io --username  ${{ secrets.ORDERWEB_REGISTRY_USERNAME }} --password ${{ secrets.ORDERWEB_REGISTRY_PASSWORD }}
            az containerapp update -n order-web -g PizzaOrderDemo4 --image cathyxwang/order-web:${{ github.sha }}
